name: composer

on: 
  push:
    branches: 
      - master # build master branch only
jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/[email protected]
      with:
        ref: master

    - name: Install
      run: |
        npm install composer
        composer install

    - name: Deploy
      uses: peaceiris/actions-gh-page[email protected]
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
